# Generated by Django 2.1.5 on 2020-01-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField(default=0)),
                ('web_lec_support', models.BooleanField(default=False)),
                ('shape', models.CharField(choices=[('oval', 'oval'), ('rectangular', 'rectangular'), ('canopy', 'canopy'), ('elevated', 'elevated')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('doj', models.DateField()),
                ('standard', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=20)),
                ('ranking', models.CharField(blank=True, max_length=10, null=True)),
                ('poc', models.ManyToManyField(to='teacher_student_api.Relative')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('chapters', models.IntegerField(default=1)),
                ('total_durations', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('doj', models.DateField()),
                ('salary', models.FloatField(default=0)),
                ('subject', models.ManyToManyField(to='teacher_student_api.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjectClassStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_student_api.Classroom')),
                ('student', models.ManyToManyField(to='teacher_student_api.Student')),
                ('subject', models.ManyToManyField(to='teacher_student_api.Subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_student_api.Teacher')),
            ],
        ),
    ]
